// Maps country names (as used in draft CSVs) to flag emojis
export const COUNTRY_FLAGS = {
  'Afghanistan': '🇦🇫',
  'Albania': '🇦🇱',
  'Algeria': '🇩🇿',
  'Andorra': '🇦🇩',
  'Angola': '🇦🇴',
  'Antigua and Barbuda': '🇦🇬',
  'Argentina': '🇦🇷',
  'Armenia': '🇦🇲',
  'Australia': '🇦🇺',
  'Austria': '🇦🇹',
  'Azerbaijan': '🇦🇿',
  'Belarus': '🇧🇾',
  'Belgium': '🇧🇪',
  'Bermuda': '🇧🇲',
  'Bolivia': '🇧🇴',
  'Brazil': '🇧🇷',
  'Bulgaria': '🇧🇬',
  'Canada': '🇨🇦',
  'Chile': '🇨🇱',
  'China': '🇨🇳',
  "People's Republic of China": '🇨🇳',
  'Chinese Taipei': '🇹🇼',
  'Colombia': '🇨🇴',
  'Costa Rica': '🇨🇷',
  'Croatia': '🇭🇷',
  'Cuba': '🇨🇺',
  'Cyprus': '🇨🇾',
  'Czech Republic': '🇨🇿',
  'Denmark': '🇩🇰',
  "Democratic People's Korea": '🇰🇵',
  "Democratic People's Republic of Korea": '🇰🇵',
  'North Korea': '🇰🇵',
  'Djibouti': '🇩🇯',
  'Dominican Republic': '🇩🇴',
  'Ecuador': '🇪🇨',
  'Egypt': '🇪🇬',
  'Estonia': '🇪🇪',
  'Ethiopia': '🇪🇹',
  'Fiji': '🇫🇯',
  'Finland': '🇫🇮',
  'France': '🇫🇷',
  'Gabon': '🇬🇦',
  'Georgia': '🇬🇪',
  'Germany': '🇩🇪',
  'Ghana': '🇬🇭',
  'Great Britain': '🇬🇧',
  'Greece': '🇬🇷',
  'Guatemala': '🇬🇹',
  'Guinea-Bissau': '🇬🇼',
  'Honduras': '🇭🇳',
  'Hong Kong': '🇭🇰',
  'Hong Kong, China': '🇭🇰',
  'Hungary': '🇭🇺',
  'Iceland': '🇮🇸',
  'India': '🇮🇳',
  'Indonesia': '🇮🇩',
  'Iran': '🇮🇷',
  'Islamic Republic of Iran': '🇮🇷',
  'Ireland': '🇮🇪',
  'Israel': '🇮🇱',
  'Italy': '🇮🇹',
  'Ivory Coast': '🇨🇮',
  'Jamaica': '🇯🇲',
  'Japan': '🇯🇵',
  'Jordan': '🇯🇴',
  'Kazakhstan': '🇰🇿',
  'Kenya': '🇰🇪',
  'Kosovo': '🇽🇰',
  'Kyrgyzstan': '🇰🇬',
  'Latvia': '🇱🇻',
  'Liechtenstein': '🇱🇮',
  'Lithuania': '🇱🇹',
  'Luxembourg': '🇱🇺',
  'Malaysia': '🇲🇾',
  'Mexico': '🇲🇽',
  'Monaco': '🇲🇨',
  'Mongolia': '🇲🇳',
  'Montenegro': '🇲🇪',
  'Morocco': '🇲🇦',
  'Netherlands': '🇳🇱',
  'New Zealand': '🇳🇿',
  'Nigeria': '🇳🇬',
  'Norway': '🇳🇴',
  'Peru': '🇵🇪',
  'Philippines': '🇵🇭',
  'Poland': '🇵🇱',
  'Portugal': '🇵🇹',
  'Puerto Rico': '🇵🇷',
  'Qatar': '🇶🇦',
  'Refugee Olympic Team': '🏳️',
  'Republic of Korea': '🇰🇷',
  'Republic of Moldova': '🇲🇩',
  'ROC': '🇷🇺',
  'Romania': '🇷🇴',
  'Russia': '🇷🇺',
  'Samoa': '🇼🇸',
  'San Marino': '🇸🇲',
  'Saudi Arabia': '🇸🇦',
  'Serbia': '🇷🇸',
  'Singapore': '🇸🇬',
  'Slovakia': '🇸🇰',
  'Slovenia': '🇸🇮',
  'South Africa': '🇿🇦',
  'South Korea': '🇰🇷',
  'Spain': '🇪🇸',
  'Sweden': '🇸🇪',
  'Switzerland': '🇨🇭',
  'Thailand': '🇹🇭',
  'Trinidad and Tobago': '🇹🇹',
  'Tunisia': '🇹🇳',
  'Turkey': '🇹🇷',
  'Turkmenistan': '🇹🇲',
  'Uganda': '🇺🇬',
  'Ukraine': '🇺🇦',
  'United States': '🇺🇸',
  'United States of America': '🇺🇸',
  'USA': '🇺🇸',
  'Uzbekistan': '🇺🇿',
  'Venezuela': '🇻🇪',
  'Vietnam': '🇻🇳',
  'Zambia': '🇿🇲',
}

export const getFlag = (country) => COUNTRY_FLAGS[country] ?? '🏳️'
